### ISSUE TITLE
wrong enchantment display on servers

### ISSUE THREAD

**Issue by clydmlndz** [CrownSheep/Enchantment-Reveal#8] opened 2024-02-23 16:45 UTC
been playing on my server and the enchantments on the e-table results in a different enchant. for example: it showed unbreaking 3 on a diamond pick and when i picked it i got efficiency 4 instead.

**Comment by CrownSheep** [comment] 2024-02-23 17:02
read issue #7, also duplicate of #2

**Closed as not planned** 2024-02-23 17:02 UTC
